Update UITransactionDlg.cpp
ko4life-net/ko pull request #204
Opened 2023-07-06 15:49 UTC by UTengine

This fixes the NPC icons being scattered around the 12 pages. 
And not being able to purchase some of them in the selling group list.

### Description
This fixes the following issue/ticket:
https://github.com/ko4life-net/ko/issues/203

💔Thank you!

2023-07-27 20:21 UTC, UTengine commented
PS/NOTE: Although this fixes npc selling icons I want this to be double tested and checked thoroughly, I don't feel okay with the loops especially if end user ends up selling an item slot that he didn't intend to sell which is a big disaster lol.

2023-07-30 23:02 UTC, stevewgr requested changes
Hi @UTengine, thanks for the PR.
The changes in the PR are wrong. We should not revert back to the old outer-loop that was fixed in here: https://github.com/ko4life-net/ko/pull/33

The only mistake here is that the `k++` have to take place in the end of the loop. I was able to reproduce on my end.

Could you please fix your PR?

2023-07-31 00:32 UTC, stevewgr commented on src/game/UITransactionDlg.cpp
> +		k++;
As discussed in Discord channel, Tahsin fixed the requested changes. Resolving.

2023-07-31 00:33 UTC, stevewgr approved these changes

2023-07-31 00:52 UTC, closed without merging

2023-07-31 01:18 UTC, stevewgr commented
Merged in here: https://github.com/ko4life-net/ko/pull/212

because the last push from @UTengine broke the PR, so I had to cherry-pick and separate commits.